const num = 4848;
prompt(`Type a number, ${num}.`);
console.log(prompt.length);
console.log(num.toString(16));
console.log(num.toString(2));
console.log(num + 2);
console.log(num * 2);
console.log(num - 2);
console.log(parseFloat((0.51000002).toFixed(2)));
console.log(parseFloat((0.51000002 + 2).toFixed(2)));
const str_one = 'the quick brown fox jumps over the lazy dogs back';
const str_two = 'brown fox jumps';
console.log(str_one.indexOf(str_two));
console.log(str_one.toUpperCase());
console.log(str_one.length);
let a = 1, b = 2, c = 3, d = 3;
console.log(a || c || b);
console.log(b || c || c);
console.log(c || c || d);
console.log(a && c && b);
console.log(a && c && b);
console.log(a && c && b);
console.log(d == 1);
console.log(a === 1);